apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dhcp-lease-pvc
  namespace: routernetes
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 512Mi
