name: Check Butane

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-butane:
    runs-on: ubuntu-latest
    container: registry.fedoraproject.org/fedora:latest
    steps:
      - name: Install butane
        run: |
          dnf -y install butane git

      - uses: actions/checkout@v3
      
      - name: Run butane
        run: |
          butane --pretty --strict ./installer/butane.yaml
