name: Build container

on:
  release:
    types: [published]
  workflow_dispatch:
  pull_request:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Buildah Action
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: routernetes
          tags: latest ${{ github.ref_name }}
          containerfiles: |
            ./Containerfile
          platforms: linux/amd64, linux/arm64
